#!/bin/sh
DATA=""

# Should the application deployed with data.
if [ "$OPENSHIFT_APP_NAME" == 'staging' ]; then
        DATA="--data=seleniumtests"
fi

echo "=Installing Passbolt="
(cd $OPENSHIFT_REPO_DIR; sh $OPENSHIFT_REPO_DIR/app/Console/cake install $DATA)
