#!/bin/sh
echo "== PRE-BUILD START ===="

echo "Setting core.php"
mv -f $OPENSHIFT_REPO_DIR/app/Config/core.php.openshift $OPENSHIFT_REPO_DIR/app/Config/core.php
echo "Setting database.php"
mv -f $OPENSHIFT_REPO_DIR/app/Config/database.php.openshift $OPENSHIFT_REPO_DIR/app/Config/database.php
echo "Setting app.php"
mv -f $OPENSHIFT_REPO_DIR/app/Config/app.php.openshift $OPENSHIFT_REPO_DIR/app/Config/app.php
echo "Setting js app.php"
mv -f $OPENSHIFT_REPO_DIR/app/webroot/js/app/config/config.json.openshift $OPENSHIFT_REPO_DIR/app/webroot/js/app/config/config.json
