#!/bin/sh
# This file is a batch script that invokes loader
# ex: documentjs/doc cookbook/cookbook.html

# Sets ..
# Absolute path to this script. /home/user/bin/foo.sh
# Absolute path this script is in. /home/user/bin


DIRNAME=`dirname "$0"`
BASENAME=`basename "$0"`
cd "${PWD}/${DIRNAME}"

DIR_OF_SCRIPT=`pwd -P`
SCRIPT="${DIR_OF_SCRIPT}/${BASENAME}"

DOCUMENTJS_ROOT=`dirname "$SCRIPT"`/
BASE=$DOCUMENTJS_ROOT

cd "$BASE"..
JMVC_ROOT="$PWD"

# classpath
CP="${JMVC_ROOT}/steal/rhino/js.jar"

# load the run.js file
LOADPATH="${BASE}/scripts/run.js"

LOADER="${JMVC_ROOT}/steal/rhino/loader"

# call the loader
. "$LOADER" $1 $2 $3 $4 $5 $6
