#!/bin/sh
#
#  preinst
#
#  Debian package pre installation script
#
#  This script takes some important steps based on the installation responses.
#
#  To display response variables for debugging the installation:
#

set -e

. /usr/share/debconf/confmodule

###########################################
# Helper internal functions
###########################################

_echo() {
  [ -z "${VERBOSE}" ] || echo ">>> $1"
}


###########################################
# Script starts here
###########################################

_echo "entering preinst script: action=$1"
