<?php
/**
 * Passbolt ~ Open source password manager for teams
 * Copyright (c) Passbolt SA (https://www.passbolt.com)
 *
 * Licensed under GNU Affero General Public License version 3 of the or any later version.
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Passbolt SA (https://www.passbolt.com)
 * @license       https://opensource.org/licenses/AGPL-3.0 AGPL License
 * @link          https://www.passbolt.com Passbolt(tm)
 * @since         2.0.0
 */
/**
 * PASSBOLT CONFIGURATION FILE
 *
 * This is a generated configuration file, which was generated by the passbolt web installer.
 *
 * To see all available options, you can refer to the default.php file, or replace this file
 * by a copy of passbolt.default.php
 * Do not modify default.php or you may break your upgrade process.
 *
 * Read more about how to install passbolt: https://www.passbolt.com/help/tech/install
 * Any issue, check out our FAQ: https://www.passbolt.com/faq
 * An installation issue? Ask for help to the community: https://community.passbolt.com/
 */
return [
    'App' => [
        // A base URL to use for absolute links.
        // The url where the passbolt instance will be reachable to your end users.
        // This information is need to render images in emails for example
        'fullBaseUrl' => 'https://dev.passbolt.local',
    ],

    // Database configuration.
    'Datasources' => [
        'default' => [
            'host' => 'db_pro_dev',
            'port' => '3306',
            'username' => 'root',
            'password' => 'P4#<b0lt',
            'database' => 'passbolt',
        ],
        'test' => [
            'host' => 'db_pro_dev_test',
            'port' => '3306',
            'username' => 'root',
            'password' => 'P4#<b0lt',
            'database' => 'passbolt',
        ],
    ],

    // Email configuration.
    'EmailTransport' => [
        'default' => [
            'host' => 'unreachable_host.dev',
            'port' => 587,
            'username' => 'webinstaller',
            'password' => 'webinstaller',
            // Is this a secure connection? true if yes, null if no.
            'tls' => true,
            //'timeout' => 30,
            //'client' => null,
            //'url' => null,
        ],
    ],
    'Email' => [
        'default' => [
            // Defines the default name and email of the sender of the emails.
            'from' => ['webinstaller@passbolt.com' => 'Webinstaller test'],
            //'charset' => 'utf-8',
            //'headerCharset' => 'utf-8',
        ],
    ],
    'debug' => true,
    'passbolt' => [
        // GPG Configuration.
        // The keyring must to be owned and accessible by the webserver user.
        // Example: www-data user on Debian
        'gpg' => [
            // Main server key.
            'serverKey' => [
                // Server private key fingerprint.
               'fingerprint' => '2FC8945833C51946E937F9FED47B0811573EE67E',
               'public' => CONFIG . DS . 'gpg' . DS . 'unsecure.key',
               'private' => CONFIG . DS . 'gpg' . DS . 'unsecure_private.key',
            ],
        ],
        'registration' => [
            'public' => true,
        ],
        'selenium' => [
            'active' => true
        ],
        'ssl' => [
            'force' => false,
        ],
        'js' => [
            'build' => 'development'
        ],
    ],
];
