# -*- coding: utf-8 -*-
#
# CakePHP Cookbook documentation build configuration file, created by
# sphinx-quickstart on Tue Jan 18 12:54:14 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# Append the top level directory of the docs, so we can import from the config dir.
sys.path.insert(0, os.path.abspath('..'))

# Pull in all the configuration options defined in the global config file..
from config.all import *

language = 'en'
